export default function Shimmer() {
  return (
    <div className="shim-container">
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
      <div className="shim-card"></div>
    </div>
  );
}
